ConnectionStrings:
  MySQL: "Server=localhost;uid=root;password=qQ123456!;Database=tgkw_db;"

Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning
    Microsoft.Hosting.Lifetime: Information